config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#welcome"
  resources :genres, only: :index do
    member do
      get "movies"
    end
  end
  resources :movies, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
    resources :rates, only: [:create, :destroy]
    member do
      get :send_info
    end
    collection do
      get :export
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates_presence_of :text, :movie_id, :user_id
  validates_uniqueness_of :user_id, scope: :movie_id
end

app/models/concerns/title_brackets_validator.rb
class TitleBracketsValidator < ActiveModel::Validator

  def validate(record)
    stack  = []
    brackets = { '(' => ')', '[' => ']', '{' => '}', '<' => '>' }
    valid = true

    record.title.each_char.with_index do |char, index|
      if brackets.key? char
        stack << [brackets[char], index]
      end

      if brackets.value? char
        bracket = stack.pop
        if bracket.nil? || bracket[0] != char || bracket[1]+1 == index
          valid = false
        end
      end
    end

    record.errors.add(:title, 'has unclosed bracket') unless stack.empty? && valid

  end
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Genre < ApplicationRecord
  has_many :genre_movies
  has_many :movies, through: :genre_movies
end

app/models/genre_movie.rb
class GenreMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/movie.rb
# == Schema Information
#
# Table name: movies
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  released_at :datetime
#  avatar      :string
#  genre_id    :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Movie < ApplicationRecord
  has_many :genre_movies
  has_many :genres, through: :genre_movies
  has_many :comments
  has_many :rates

  validates_with TitleBracketsValidator
  self.per_page = 10

  def self.search(search)
    if search
      where('title LIKE ?', "#{search}")
    else
      all
    end
  end
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates_presence_of :rating, :movie_id, :user_id
  validates_uniqueness_of :user_id, scope: :movie_id
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :comments
  has_many :rates
  validates :phone_number,
            format: { with: /\A[+]?\d+(?>[- .]\d+)*\z/, allow_nil: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    if comment.save
      redirect_to movie_path(params[:movie_id]), notice: 'Comment was succesfully created'
    else
      redirect_to movie_path(params[:movie_id]), alert: 'Comment was not created'
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    if current_user.id == comment.user_id
      comment.destroy
      redirect_to movie_path(params[:movie_id]), notice: 'Comment was destroy'
    else
      redirect_to movie_path(params[:movie_id]), alert: 'Comment was not destroy'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :user_id, :movie_id)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.decorate
  end

  def movies
    @genre = Genre.find(params[:id]).decorate
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome; end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:send_info]

  def index
    @movies = Movie.preload(:genre_movies).paginate(page: params[:page]).search(params[:movie_s]).decorate
  end

  def show
    @movie = Movie.find(params[:id]).decorate
    @comments = Comment.all
    @rates = Rate.all
  end

  def send_info
    @movie = Movie.find(params[:id])
    MovieInfoMailer.send_info(current_user, @movie).deliver_now
    redirect_to :back, notice: "Email sent with movie info"
  end

  def export
    file_path = "tmp/movies.csv"
    MovieExporter.new.call(current_user, file_path)
    redirect_to root_path, notice: "Movies exported"
  end
end

app/controllers/rates_controller.rb
class RatesController < ApplicationController

  def create
    rate = current_user.rates.build(rate_params)
    if rate.save
      redirect_to movie_path(params[:movie_id]), notice: 'Rate was succesfully created'
    else
      redirect_to movie_path(params[:movie_id]), alert: 'Rate was not created'
    end
  end

  def destroy
    rate = Rate.find(params[:id])
    if current_user.id == rate.user_id
      rate.destroy
      redirect_to movie_path(params[:movie_id]), notice: 'Rate was destroy'
    else
      redirect_to movie_path(params[:movie_id]), alert: 'Rate was not destroy'
    end
  end

  private

  def rate_params
    params.require(:rate).permit(:rating, :movie_id, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/views/comments/_form.html.haml
= form_for [movie, comment] do |f|
  = f.hidden_field :movie_id
  = f.hidden_field :user_id
  = f.text_area :text, cols: 50, rows: 5, placeholder: "Write new comment"
  %br
  = f.submit 'Create comment', class: 'btn btn-default'

app/views/genres/index.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center All genres
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Name
          %th Number of movies
          %th Created at
      %tbody
        - @genres.each_with_index do |genre, i|
          %tr
            %td= i + 1
            %td= genre.name
            %td= genre.number_of_movies
            %td= genre.created_at

app/views/genres/movies.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center
      Movies by genre:
      = @genre.name
    = render 'movies/movies_table', movies: @genre.movies

app/views/home/welcome.html.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Welcome to Pairguru App!
    %p.lead.text-center Place where we examine our candidates

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Pairguru App', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links.html.haml
%li= link_to 'Movies', movies_path
%li= link_to 'Genres', genres_path
- if user_signed_in?
  %li= link_to 'Export', export_movies_path

app/views/layouts/_navigation_links_right.html.haml
- if user_signed_in?
  %li= link_to 'Logout', destroy_user_session_path, method: :delete
- else
  %li= link_to 'Login', new_user_session_path
  %li= link_to 'Register', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Pairguru'
    %meta{ name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Props'}" }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #announcements-region
    %header
      #header-region
        = render 'layouts/navigation'
    %main
      .container
        #main-region
        = render 'layouts/messages'
        = yield
    %footer.text-center
      Magic by
      = link_to 'netguru', 'https://netguru.co'

app/views/movies/_movies_table.html.haml
%table.table.table-striped
  %tbody
    - movies.each_with_index do |movie, i|
      %tr
        %td= i + 1
        %td
          = image_tag(MovieApiCover.poster(movie.title, movie.cover), size: "170x244")
        %td
          %h4
            = link_to movie.title, movie_path(movie)
          %p
            %strong
              - movie.genres.each do |genre|
                = link_to genre.name, movies_genre_path(movie.genres)
            = ' (' + movie.released_at.to_s + ')'
          %p= MovieApiPlot.plot(movie.title, movie.description)

app/views/movies/_search.html.haml
= form_tag movies_path, method: :get do
  = text_field_tag :movie_s, params[:movie_s]
  = submit_tag 'Search', name: nil

app/views/movies/index.html.haml
= render "movies/search"
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Movies
    = render 'movies_table', movies: @movies
= will_paginate @movies

app/views/movies/show.html.haml
%h1= @movie.title
.jumbotron
  .col-md-6.col-md-offset-2.col-lg-2.col-lg-offset-0
    = image_tag(MovieApiCover.poster(@movie.title, @movie.cover), size: "320x458")
  .col-md-6.col-md-offset-2.col-lg-8.col-lg-offset-2
    = MovieApiPlot.plot(@movie.title, @movie.description)
  %br
  %br
  .col-md-6.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h4
      Rating
      = MovieApiRating.rating(@movie.title)
- if user_signed_in?
  .text-center
    %p= link_to 'Email me details about this movie', send_info_movie_path(@movie), class: 'btn btn-sm btn-default'
    = render "comments/form", movie: @movie, comment: Comment.new(movie_id: @movie.id, user_id: current_user.id)
%h3.text-center
  Comments
%table.table
  %thead
  %tbody
    %tr
    - @comments.each do |comment|
      %td= comment.text
      %td= comment.decorate.user_name
      %td
        = link_to [@movie, comment], method: :delete do
          %button.btn.btn-default
            = fa_icon "times"

    = render "rates/form", movie: @movie, rate: Rate.new(movie_id: @movie.id, user_id: current_user.id)
%h3.text-center
  Rates
%table.table
  %thead
  %tbody
    %tr
    - @rates.each do |rate|
      %td= rate.rating
      %td
        = link_to [@movie, rate], method: :delete do
          %button.btn.btn-default
            = fa_icon "times"

app/views/rates/_form.html.haml
= form_for [movie, rate] do |f|
  = f.hidden_field :movie_id
  = f.hidden_field :user_id
  = f.text_area :rating, cols: 50, rows: 5, placeholder: "Write new comment"
  %br
  = f.submit 'Create rate', class: 'btn btn-default'